#!/usr/bin/env bash
set -euo pipefail

# AgentPay — Deploy all Soroban contracts to Stellar testnet
cd "$(dirname "$0")/.."

RPC_URL="https://soroban-testnet.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
WASM_DIR="target/wasm32-unknown-unknown/release"

echo "=============================================="
echo "  AgentPay — Contract Deployment"
echo "=============================================="
echo ""

# Generate deployer identity if not exists
if ! stellar keys address agentpay-deploy 2>/dev/null; then
  echo "Generating deployer identity..."
  stellar keys generate agentpay-deploy --fund --rpc-url "$RPC_URL" --network-passphrase "$PASSPHRASE"
fi
DEPLOYER=$(stellar keys address agentpay-deploy)
echo "  Deployer: $DEPLOYER"

# Helper: deploy contract and extract ID from Soroban RPC
deploy_contract() {
  local name=$1
  local wasm=$2

  echo ""
  echo "--- Deploying $name ---"

  # Deploy (CLI may error on XDR post-processing but tx succeeds)
  local output
  output=$(stellar contract deploy \
    --wasm "$wasm" \
    --source agentpay-deploy \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$PASSPHRASE" 2>&1 || true)

  # Extract tx hash from output
  local tx_hash
  tx_hash=$(echo "$output" | grep -oP 'Transaction hash is \K[a-f0-9]+' | tail -1)

  if [ -z "$tx_hash" ]; then
    # If no tx hash, maybe it succeeded and printed the contract ID directly
    local maybe_id
    maybe_id=$(echo "$output" | grep -oP '^C[A-Z0-9]{55}$' || true)
    if [ -n "$maybe_id" ]; then
      echo "  Contract: $maybe_id"
      echo "$maybe_id"
      return 0
    fi
    echo "  ERROR: Could not find tx hash in output:"
    echo "$output"
    return 1
  fi

  # Extract contract ID from Soroban RPC using the tx hash
  local contract_id
  contract_id=$(cd packages/sdk && node -e "
const { rpc, StrKey } = require('@stellar/stellar-sdk');
const server = new rpc.Server('$RPC_URL');
async function getContract() {
  // Wait a moment for tx to finalize
  for (let i = 0; i < 10; i++) {
    try {
      const tx = await server.getTransaction('$tx_hash');
      if (tx.status === 'SUCCESS' && tx.returnValue) {
        if (tx.returnValue.switch().name === 'scvAddress') {
          const addr = tx.returnValue.address();
          if (addr.switch().name === 'scAddressTypeContract') {
            console.log(StrKey.encodeContract(addr.contractId()));
            return;
          }
        }
      } else if (tx.status === 'NOT_FOUND') {
        await new Promise(r => setTimeout(r, 2000));
        continue;
      }
    } catch(e) {
      await new Promise(r => setTimeout(r, 2000));
    }
  }
  console.error('Failed to get contract ID');
  process.exit(1);
}
getContract();
  ")

  echo "  Contract: $contract_id"
  echo "$contract_id"
}

# Deploy all three contracts
REGISTRY_ID=$(deploy_contract "ServiceRegistry" "$WASM_DIR/service_registry.wasm")
REGISTRY_ID=$(echo "$REGISTRY_ID" | grep '^C[A-Z0-9]' | tail -1)

BUDGET_ID=$(deploy_contract "BudgetPolicy" "$WASM_DIR/budget_policy.wasm")
BUDGET_ID=$(echo "$BUDGET_ID" | grep '^C[A-Z0-9]' | tail -1)

RECEIPT_ID=$(deploy_contract "ReceiptLedger" "$WASM_DIR/receipt_ledger.wasm")
RECEIPT_ID=$(echo "$RECEIPT_ID" | grep '^C[A-Z0-9]' | tail -1)

echo ""
echo "--- Initializing contracts ---"

# Initialize each contract
for pair in "ServiceRegistry:$REGISTRY_ID" "BudgetPolicy:$BUDGET_ID" "ReceiptLedger:$RECEIPT_ID"; do
  name="${pair%%:*}"
  id="${pair#*:}"
  echo -n "  $name... "
  stellar contract invoke \
    --id "$id" \
    --source agentpay-deploy \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$PASSPHRASE" \
    -- initialize \
    --admin "$DEPLOYER" 2>&1 && echo "done" || echo "already initialized"
done

echo ""
echo "=============================================="
echo "  Deployment Complete!"
echo "=============================================="
echo ""
echo "SERVICE_REGISTRY_CONTRACT=$REGISTRY_ID"
echo "BUDGET_POLICY_CONTRACT=$BUDGET_ID"
echo "RECEIPT_LEDGER_CONTRACT=$RECEIPT_ID"
echo ""

# Write .env file
cat > .env <<EOF
# AgentPay — Environment Configuration (auto-generated by deploy.sh)

STELLAR_NETWORK=testnet

# Contract IDs
SERVICE_REGISTRY_CONTRACT=$REGISTRY_ID
BUDGET_POLICY_CONTRACT=$BUDGET_ID
RECEIPT_LEDGER_CONTRACT=$RECEIPT_ID

# Deployer
DEPLOYER_ADDRESS=$DEPLOYER

# x402 Facilitator
FACILITATOR_URL=https://x402.org/facilitator
EOF

echo "  .env file written with contract IDs"
echo ""
